# Generated by Django 2.2.28 on 2022-06-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='closed',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date closed'),
        ),
    ]
