# Generated by Django 2.2.28 on 2022-06-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220607_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='registration_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
