# Generated by Django 2.2.28 on 2022-06-16 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_post_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loststatus',
            name='post_found_id',
        ),
        migrations.RemoveField(
            model_name='loststatus',
            name='post_search_id',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='LostStatus',
        ),
    ]
